/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentacionbanco;

import com.mycompany.dominiobanco.Cliente;
import com.mycompany.dominiobanco.Cuenta;
import com.mycompany.dominiobanco.Transaccion;
import conexion.IConexion;
import dao.ICuentaDAO;

/**
 *
 * @author ID145
 */
public class ConfirmacionTransferencia extends javax.swing.JFrame {

    private Cliente cliente;
    private Cuenta cuenta;
    private ICuentaDAO cuentaDAO;
    private final IConexion conexion;
    /**
     * Creates new form ConfirmacionTransferencia
     */
    public ConfirmacionTransferencia(Cliente cliente, Cuenta cuenta, Transaccion transacccion, String cuentaDestino, ICuentaDAO cuentaDAO, IConexion conexion) {
        initComponents();
        this.cuentaDAO = cuentaDAO;
        this.conexion = conexion;
        this.cuenta = cuenta;
        this.cliente = cliente;
        
        String saludo = txtSaludo.getText().replaceAll("Usuario", cliente.getNombres());
        txtSaludo.setText(saludo);

        txtIDeTarjeta.setText("Tarjeta " + cuenta.getNumero());
        txtCantidad.setText("Cantidad: " + transacccion.getMonto());
        txtNumeroCuentaDestino.setText("Numero de cuenta: " + cuentaDestino);
        txtFechaHora.setText("Fecha y Hora: " + transacccion.getFecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtFechaHora = new javax.swing.JLabel();
        txtSaludo = new javax.swing.JLabel();
        txtTransferenciaRealizada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JLabel();
        txtNumeroCuentaDestino = new javax.swing.JLabel();
        txtIDeTarjeta = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        btnCrearTarjetas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 30));

        txtFechaHora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtFechaHora.setForeground(new java.awt.Color(51, 51, 51));
        txtFechaHora.setText("Fecha y Hora:");
        jPanel1.add(txtFechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        txtSaludo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSaludo.setForeground(new java.awt.Color(51, 51, 51));
        txtSaludo.setText("¡Hola, Usuario!");
        jPanel1.add(txtSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        txtTransferenciaRealizada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTransferenciaRealizada.setForeground(new java.awt.Color(51, 51, 51));
        txtTransferenciaRealizada.setText("Transferencia Realizada con exito!");
        jPanel1.add(txtTransferenciaRealizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Transferencia Realizada con exito!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(51, 51, 51));
        txtCantidad.setText("Cantidad:");
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        txtNumeroCuentaDestino.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNumeroCuentaDestino.setForeground(new java.awt.Color(51, 51, 51));
        txtNumeroCuentaDestino.setText("Numero de cuenta:");
        jPanel1.add(txtNumeroCuentaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        txtIDeTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIDeTarjeta.setForeground(new java.awt.Color(51, 51, 51));
        txtIDeTarjeta.setText("Tarjeta");
        jPanel1.add(txtIDeTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setText("Banco");
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnCrearTarjetas.setText("Volver");
        btnCrearTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTarjetasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTarjetasActionPerformed
        Tarjeta tarjeta = new Tarjeta(cliente, cuenta, conexion, cuentaDAO);
        tarjeta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearTarjetasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearTarjetas;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtCantidad;
    private javax.swing.JLabel txtFechaHora;
    private javax.swing.JLabel txtIDeTarjeta;
    private javax.swing.JLabel txtNumeroCuentaDestino;
    private javax.swing.JLabel txtSaludo;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtTransferenciaRealizada;
    // End of variables declaration//GEN-END:variables
}
